server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: feedback-service
          uri: http://${FEEDBACK_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/feedback
            - Method=GET
          filters:
            - SetPath=/api/feedback/all
        - id: student-service
          uri: http://${STUDENT_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/students
            - Method=GET
          filters:
            - SetPath=/api/students
        - id: course-service
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses
            - Method=GET
          filters:
            - SetPath=/api/courses
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 4
                redis-rate-limiter.requestedToken: 1
        - id: course-service-create
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses
            - Method=POST
          filters:
            - SetPath=/api/courses
        - id: course-service-update
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses/{id}
            - Method=PUT
          filters:
            - SetPath=/api/courses/{id}
        - id: course-service-delete
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/courses/{id}
        - id: course-service-students
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses/students/{courseNumber}
            - Method=GET
          filters:
            - SetPath=/api/courses/{courseNumber}/students
        - id: course-service-feedback
          uri: http://${COURSE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/courses/feedback/{courseNumber}
            - Method=GET
          filters:
            - SetPath=/api/courses/{courseNumber}/feedback
